name: Template Build

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: Install .NET (v6.0)
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore
      - name: Test
        run: |
          dotnet test --configuration Release
      - name: Pack
        run: dotnet pack src/Cliy.Template.csproj --configuration Release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cliy.${{ matrix.os }}
          path: src/bin/Release/

  publish:
    if: contains(github.ref, 'tags/v') # only publish tagged versions
    needs: [test]
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v3
      - name: Install .NET (v6.0)
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x
      - name: Extract version
        id: extract_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
        shell: bash
      - name: Build
        run: |
          dotnet pack src/Cliy.Template.csproj --configuration Release --version-suffix ${{ steps.extract_version.outputs.version }}
          ls -l src/bin/Release
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          name: Release ${{ steps.extract_version.outputs.version }}
          body: |
            [Changelog](https://github.com/codito/Cliy/blob/master/CHANGELOG.md)
          artifacts: "src/bin/Release/*.nupkg"
          token: ${{ secrets.GITHUB_TOKEN }}
